# Project information
site_name: CMap SigTool Documentation
site_author: Connectivity Map

# Repository
repo_name: cmap/cmap-sig-tools
repo_url: https://github.com/cmap/cmap-sig-tools
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Connectivity Map

nav:
  - Home: index.md
  - Command Reference: 
    - Shared arguments: command-reference/shared_arguments.md
    - Connectivity analysis:
        queryl1k: command-reference/sig_queryl1k_tool.md
        gseapreranked: command-reference/sig_gseapreranked_tool.md
        curie: command-reference/sig_curie_tool.md
        introspect: command-reference/sig_introspect_tool.md
        recall: command-reference/sig_recall_tool.md        
        gutc: command-reference/sig_gutc_tool.md
    - Expression analysis:        
        marker: command-reference/sig_marker_tool.md
        pca: command-reference/sig_pca_tool.md
        tsne: command-reference/sig_tsne_tool.md
    - Utilities:
        annotate: command-reference/sig_annotate_tool.md
        slice: command-reference/sig_slice_tool.md        
        collate: command-reference/sig_collate_tool.md        
        getgenesets: command-reference/sig_getgenesets_tool.md        
        score2rank: command-reference/sig_score2rank_tool.md
        testmlr: command-reference/sig_testmlr_tool.md
        trainmlr: command-reference/sig_trainmlr_tool.md        
        zscore: command-reference/sig_zscore_tool.md
  - Tutorials:
    - Running SigTools in MATLAB: matlab_demo.md
    - Running SigTools with Docker: docker_demo.md 

  - FAQ: faq.md
 
theme:
  name: material
  custom_dir: overrides
  # CMap favicon
  favicon: img/favicon.ico
  logo: img/banner-logo.svg
extra:
  generator: false 
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences